### ISSUE TITLE
onDrag not called when remove a finger 

### ISSUE THREAD

**Issue by minnits** [pmndrs/react-use-gesture#170]
First, thanks for all your work.

I have a little issue on the lib : If I drag an item with two fingers, onDrag is called (perfect for my usecase) but when i remove one  finger (there is still one finger moving on the item), the function onDrag is not called anymore. If i put two fingers again on the item, onPinch is called but not onDrag.

Thank you.

**Comment by dbismut** [comment]
Thanks! Well, in theory onDrag shouldn’t trigger with two fingers... Let me check what happens there. You need two fingers padding + pinching, is that it? That might be a bit complex to handle and would add a lot of logic to the lib I’m afraid.

**Comment by minnits** [comment]
Wow you are really fast :) 

If draging is not working with more than one finger it's ok i can handle it but in this case, if we pass from two finger to one finger onDrag function should fire ?

**Comment by dbismut** [comment]
Hmmm onDrag should only fire onTouchStart or onMouseDown so I don’t think it should trigger...

**Comment by dbismut** [comment]
(I keep checking for react-spring to update before I go to sleep ;)

**Comment by dbismut** [comment]
Hey @minnits!
So I just checked and drag won't start if there's more than 1 finger on the target.

What happens though is that if your second finger isn't detected (ie it is indeed touching the screen but isn't touching the target although it might seem very close to it), the drag will start.

The element target is only responsible for initiating the drag, future `touchMove` and `touchEnd` events are then delegated to the `window`, which means that the second, non originally-detected finger, **is tracked by the `window`**.

 The `dragEnd` event is triggered on `touchEnd` on the window element, but it doesn't check how many fingers are left on screen. Meaning that if any of your fingers are lift up during the drag, the drag will stop even though you still have a finger in contact with your target element.

So I guess this boils down to this:

- **Is this an acceptable behavior?** I would say yes, but it can be improved in making non-initiating touches irrelevant for future interactions.
- **Should the drag NOT start if two touches are detected on screen (whether on target or not)?** This would require adding a global window listener, which might be a bit of an overkill within the scope of this lib.
- **Should there be an option to let users pan with two fingers while being able to pinch?** you tell me, but this would require a significant amount of logic to detect a  drag from a pinch if both need to respond to two fingers.

**Comment by minnits** [comment]
Hi @dbismut, maybe i'm doing something wrong on my side but drag works with more than one finger on the target, i made a small exemple here using spring example : https://codesandbox.io/s/hopeful-waterfall-s4ccr?file=/src/index.js

I can drag with 1/2/3 fingers, with fingers on the target. 

I think when a finger is detected on the target, drag start and then active the drag on the window. After that the second point is detected on the target, drag is already declared on the window so it is not start again but not canceled too that's why we can drag with more than one finger in my opinion. 

I see an other limitation of the lib, we can't interact with two items at the same time (drag two items) that's a problem too for me. Unfortunately I think i need to go deeper in the js touchevent to get it working as i want :/

Ps: I saw you are french i'm too ;)

**Comment by dbismut** [comment]
Ok let me import this into my examples locally so I debug this. Indeed, interacting with two targets should be possible within the scope of this lib.

**Comment by dbismut** [comment]
@minnits ok so it happens when the second finger touches the element \*after\* the first touch is registered. Let me see how I can fix this, possibly in a future release.

**Comment by dbismut** [comment]
Here is a simplified sandbox for reference: https://codesandbox.io/s/wild-grass-71o9d

**Comment by dbismut** [comment]
Hey @minnits try this https://urwww.csb.app/ which pulls PR #164 and that allows to divs to be dragged independently from each other.

I still need to fix something with pinching but that's closer to what you were expecting right?

**Comment by minnits** [comment]
@dbismut nice, possible to pinch the two items at the same time too ?

**Comment by dbismut** [comment]
You mean with four fingers?

**Comment by minnits** [comment]
yes i mean one hand with two finger on one item and one hand with two fingers on the second

**Comment by dbismut** [comment]
😅 that’s a tough one for the scope of this lib. Out of the top of my head it would probably require the two touches to start inside the component element (which is a strong constraint for small targets). Or possibly to have at least one one target and the other one close enough. I’ll have a shot over the week-end.

**Comment by minnits** [comment]
lol, yes two fingers must start on the item and interact only with this item (with the card example you can easily put two fingers on the frame). I'm used to C++ development, touch are handle like this in components. Last week, I achieve to make a working demo with angular and hammer.js corresponding to this behavior and i'm trying to do the same with React because i prefer React :). Don't tie yourself in knots for that ^^

**Comment by dbismut** [comment]
@minnits finally got the time to have a look at this, turns out it was simpler than expected, using `targetTouches` instead of `touches` did the trick. Have a look at updated:  https://urwww.csb.app/

**Comment by minnits** [comment]
@dbismut nice that's exactly what i need ! How can i use it ? I need to link a special package like you did in your demo ? Any chance that these new changes take place in the release library ?
Thank you :)

**Comment by dbismut** [comment]
Yes for the moment it’s only available from the PR #164 

I’m not sure when it will be ready as @thephoenixofthevoid is performing some structural changes. We’ll also release a beta first as it includes some breaking changes that may cause some trouble in some situations.

**Comment by minnits** [comment]
@dbismut everything works perfectly in my app thanks a lot :)
