### ISSUE TITLE
🔮 v8.0.0 beta available

### ISSUE THREAD

**Issue by dbismut** [pmndrs/react-use-gesture#180]
Hi all,

React Use Gesture v8.0.0 is now available on npm with the `next` tag. You can install it by typing the following command:

```bash
# using yarn
yarn add react-use-gesture@next 

# using npm
npm install react-use-gesture@next
```

## Internal changes

**`v8.0.0` is a major rework and refactoring of the code aiming at better structure and performance improvements across renders, thanks to @thephoenixofthevoid.**

### Pointers (could be controversial)
The library now resorts to pointer events extensively: this simplifies some of the drag logic significantly, but has two main implications:

1. The `{ eventOptions: { pointer: true } }` option is now gone. This means that react-use-gesture works out of the box with [react-three-fiber](https://github.com/react-spring/react-three-fiber) 💁‍♂️

2. [Because scrolling cancels pointer events on touch screens](https://javascript.info/pointer-events#event-pointercancel), you will need to style your element with `touch-action: <value>` to make sure the dragging can work properly. [The docs for touch-action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action).

### domTarget option no longer requires useEffect in user land.

When adding events directly to the dom element using `domTarget` you no longer need to clean the effect yourself.

```jsx
// before
const bind = useDrag(() => { /* your logic */ }, { domTarget: window })
React.useEffect(bind, [bind])

// after
useDrag(() => { /* your logic */ }, { domTarget: window })
```

### Non intentional movements will always fire your handler

This aims at working with the `threshold / filterTaps` option.

In React Use Gesture v7, if you had set the drag `threshold` option to `10`, your `useDrag` handler would only fire when the `x` or `y` displacement of the user gesture would be greater than `10`. This is no longer the case in v8. Your handler will fire as soon as the drag is initiated.

```jsx
useDrag(({ down, active, movement: [mx] }) => console.log({ down, active, mx }), { threshold: 10 })

// BEFORE
// mouse down        --> <no output>
// mouse moves 8px   --> <no output>
// mouse moves 10px  --> { down: true, active: true,  mx: 10 }

// AFTER
// mouse down        --> { down: true, active: false, mx: 0 }
// mouse moves 8px   --> { down: true, active: false, mx: 0 }
// mouse moves 10px  --> { down: true, active: true,  mx: 10 }
```

This means that if you have some complex logic in your handler, you may want to wrap it into like so:

```jsx
useDrag(({ active }) => {
  if(active) {
    /* your complex logic */
  }
}, { threshold: 10 })
```

This changes makes it easy to access initial `pointerdown` and subsequent `pointermove` events in userland, and possibly `stopPropagation` or `preventDefault`.

## Added features
v8.0.0 doesn't add many features but:

1. Drag and pinch now works on multiple dom elements at once [#170](https://github.com/react-spring/react-use-gesture/issues/170).
2. Drag option `{ filterTaps: true }` will also prevent unwanted taps on children elements [#173](https://github.com/react-spring/react-use-gesture/issues/173).

### Remaining to be done
- [x] Make handlers extensible for react-three-fiber #182
- [x] Fix some types
- [x] Testing
- [x] Tree shaking
- [x] Better API for `active` when used with `filterTaps`, `threshold`, etc.
- [x] Test with React 17

# Happy testing 🕹

**Comment by n1ru4l** [comment]
Hey there, I tried building a simple drag/pinch zoom-image component with these changes and I am struggling with the behaviour on an iPad. When the pinch-zoom has ended (I remove the two fingers from the display) the content is moved as if the drag event listener was invoked (for the one finger that is removed last) afterwards.

Additionally, I cannot comprehend how to correctly use pinch-zoom in the browser. "Natural" zoom is still happening despite the domTarget and passive event config being set.

Furthermore, I have a hard time understanding how I could implement pinch-zoom based on the center of the pinch-zoom gesture instead of the center of the component.

I would really appreciate any help regarding that 😅

I created this CodeSandbox: https://codesandbox.io/s/practical-shtern-e5qfy

**Comment by thephoenixofthevoid** [comment]
Try to comment out the line 60:
```
// if (pinching || canceled) return;
```
On my Android it works perfectly then. Please, let us know if it helps.

**Comment by n1ru4l** [comment]
@thephoenixofthevoid I am assuming you are commenting regarding:
> Hey there, I tried building a simple drag/pinch zoom-image component with these changes and I am struggling with the behaviour on an iPad. When the pinch-zoom has ended (I remove the two fingers from the display) the content is moved as if the drag event listener was invoked (for the one finger that is removed last) afterwards.

That did not change anything in the behaviour on my iPad. I have no android phone so I cannot test that there. I am currently uploading a video that will show-case this issue.

https://drive.google.com/file/d/1-qp4thS95e2JEKLRmr7xWJfL6AdJc-hv/view?usp=sharing

Also the updated CodeSandbox (as a reference): https://codesandbox.io/s/magical-rgb-30gv5?file=/src/App.js

**Comment by thephoenixofthevoid** [comment]
Please, record the same interactions with the following app: https://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud.html
So that the debug information is clearly visible (you will get it when open the link).

**Comment by n1ru4l** [comment]
@thephoenixofthevoid Here: https://drive.google.com/file/d/1IlKZaHf6dIvNUziKLA2ba9SlY2Di50xX/view?usp=sharing

**Comment by n1ru4l** [comment]
Okay I did some more testing and on iPad Safari there is definitely no `origin` passed to the `onPinch` handler.

**Comment by dbismut** [comment]
@n1ru4l we're working on this. The `origin` issue is related to #152.

**Comment by dbismut** [comment]
We've just released `8.0.0-alpha.2` which should at least fix the `origin` problem I believe.

**Comment by n1ru4l** [comment]
@dbismut I can confirm that the origin issue does no longer exist in `8.0.0-alpha.2` (https://codesandbox.io/s/react-three-fiber-react-use-drag-ux9w5?file=/src/App.js)

**Comment by n1ru4l** [comment]
Is there any content on how to do nested `useDrag`/`useGesture` with react-three-fiber?

I wanna have a drag handler for changing the x/y coordinates of the outer element and one for the inner element. I do not understand how I can cancel the inner event in orde to not propagate to the outer drag handler.

**Comment by dbismut** [comment]
@n1ru4l I'm on my phone atm but have a look at https://codesandbox.io/embed/old-shadow-uq7mt?codemirror=1. The inner orange square drag doesn't propagate to its parent.

**Comment by n1ru4l** [comment]
@dbismut Thanks, the example works, fine. I also upgraded it to 8.0.0-alpha.2 it still works. However, when trying to do this locally (with the same dependencies) it works most of the time, but infrequently I have the issue that both elements are dragged at the same time. When adding onPointerDown callback to the outer element this confirms that sometimes the outer callback is invoked first. I will try to share a minimal reproduction tomorrow.

**Comment by n1ru4l** [comment]
https://github.com/react-spring/react-use-gesture/issues/180#issuecomment-640911024

I solved this by using two event handlers. One attached the document via `domTarget` for the onPinch event and one attached to the element via `bind()` for the drag gesture. I have an additional `ref` that stores whether a drag is in process so that the two handlers do not interfere.

It seems to work quite well on iOS Safari, Chrome Desktop and Firefox desktop.

I get the following error on Safari Desktop for the pinch gesture:

![image](https://user-images.githubusercontent.com/14338007/87780718-92cabe00-c82f-11ea-8cf2-fe624403750d.png)

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
_nonIterableRest
node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/nonIterableRest.js:2
  1 | export default function _nonIterableRest() {
> 2 |   throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
  3 | }
View compiled
onPinch
src/map-view.tsx:706
  703 |     isDragDisabledRef.current = false;
  704 |   }, 100);
  705 | },
> 706 | onPinch: ({ movement, event, origin, ctrlKey, last, cancel }) => {
      | ^  707 |   if (!viewport || !event || !dimensions) {
  708 |     return;
  709 |   }
View compiled
fn
src/hooks/useGesture.ts:86
  83 | const fn = (state: any) => {
  84 |   let memo: any = undefined
  85 |   if (state.first && startKey in handlers) handlers[startKey]!(state)
> 86 |   if (handlerKey in handlers) memo = handlers[handlerKey]!(state)
     | ^  87 |   if (state.last && endKey in handlers) handlers[endKey]!(state)
  88 |   return memo
  89 | }
View compiled
fireGestureHandler
src/recognizers/Recognizer.ts:192
  189 | } as FullGestureState<T>
  190 | 
  191 | // @ts-ignore
> 192 | const newMemo = this.handler(state)
      | ^  193 | 
  194 | // Sets memo to the returned value of the handler (unless it's not undefined)
  195 | this.state.memo = newMemo !== void 0 ? newMemo : this.state.memo
View compiled
onGestureChange
src/recognizers/PinchRecognizer.ts:121
  118 |     ...kinematics,
  119 |   })
  120 | 
> 121 |   this.fireGestureHandler()
      | ^  122 | }
  123 | 
  124 | onGestureEnd = (event: WebKitGestureEvent): void => {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```

**Comment by dbismut** [comment]
Hi @n1ru4l is it possible to provide a repro sandbox? I'll try to have a look over the week-end.

**Comment by n1ru4l** [comment]
@dbismut Sorry, I will not be able to provide a reproduction on codesandbox this weekend. However you can find the complete code over here: https://github.com/dungeon-revealer/dungeon-revealer/pull/587/files#diff-a83c2e3bdae6f0939ac8bf099cca9466

**Comment by raop155** [comment]
@dbismut 
Make my app with create-react-app 
This version (v8.8.8a) works amazing in dev mode.
But in production does not work simply i get an empty view.

My deps:
```
"dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "lodash.clamp": "^4.0.3",
    "node-sass": "^4.14.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hammerjs": "^1.0.1",
    "react-player": "^2.6.1",
    "react-router-dom": "^5.2.0",
    "react-router-transition": "^2.0.0",
    "react-scripts": "3.4.3",
    "react-spring": "^9.0.0-rc.3",
    "react-transition-group": "^4.4.1",
    "react-use-gesture": "^8.0.0-alpha.2",
    "use-sound": "^1.0.2"
  }
```

**Comment by dbismut** [comment]
Hi @raop155 thanks for testing the alpha, much appreciated. Are there any error messages in your console? Are you positive this is because of react-use-gesture? Is there a way for you to create a minimal repro sandbox?

**Comment by raop155** [comment]
> Hi @raop155 thanks for testing the alpha, much appreciated. Are there any error messages in your console? Are you positive this is because of react-use-gesture? Is there a way for you to create a minimal repro sandbox?

@dbismut 
Make it work, it was a bug in my code, where i put some comment in my render function but it work in DEV, but in PROD it was just a blank page with no errors in console.
Solution: erased all comments

Thanks

**Comment by n1ru4l** [comment]
The issues mentioned in https://github.com/pmndrs/react-use-gesture/issues/180#issuecomment-660050674 do no longer exist in `8.0.0-alpha.4` 🎉

Would it be possible to type the `event` property passed into the `onWheel` handler of `useGesture` to `WheelEvent | React.WheelEvent | undefined` instead of `UIEvent | React.UIEvent<Element, UIEvent> | undefined`? In which case would `event` be `undefined`? Is the `undefined` typing even necessary?

**Comment by dbismut** [comment]
@n1ru4l indeed you're right! I'll check about removing undefined, but `8.0.0-alpha.5` should have the correct event typing in the handlers, please let me know if this works?

**Comment by dbismut** [comment]
Now `8.0.0-alpha.6` has `event` defined in handlers.

**Comment by n1ru4l** [comment]
@dbismut I will test it sometime this weekend :) Thanks for the awesome work!

**Comment by n1ru4l** [comment]
@dbismut Could it be possible that there is no longer a `state.point` passed into the `onPointerDown` `useGesture` argument? It was never documented or typed AFAIK. But I used it for convenience so I don't have to calculate the pointer coordinates on the plane via the clientX/Y of the event. Is this intended? (See https://github.com/dungeon-revealer/dungeon-revealer/blob/24b13ef992f8247606dfbf743ae5f8505b4db6bc/src/map-view.tsx#L576).

`event` is now defined everywhere and the typings are more correct! Awesome 🎉

**Comment by dbismut** [comment]
@n1ru4l yes `origin` can be `undefined` when people are zooming with a trackpad, there's no origin in that case.

Regarding the `event` parameter, you're using it in a native handler, so at this time it's just an `Event`. That could be improved to match the event type of the handler, but that wouldn't solve the fact that there's no way the lib could guess you're using r3f and cast it to a `ReactThreeFiber.PointerEvent` all by itself!

**Comment by n1ru4l** [comment]
@dbismut I am zooming with my MacBook trackpad and it seems like there is an origin 😅.

I understand the issue with the `event` parameter. Maybe it could be possible to have an `isPointerEvent` function exported from react-three-fibe with the signature `(input: unknown) => input is ReactThreeFiber.PointerEvent`.

**Comment by dbismut** [comment]
@n1ru4l I should have been clearer sorry. You're probably zooming with Safari. But pinching also supports zooming with more standard trackpads, using the wheel while pressing the ctrl key. In that case, no origin 🤷‍♂️ you can try with Chrome.

Regarding the typing issue with r3f, the user should be responsible for which event it expects from the handler, I think casting should be a better solution. I'll try to work on sth when I have time.

**Comment by n1ru4l** [comment]
> @n1ru4l I should have been clearer sorry. You're probably zooming with Safari. But pinching also supports zooming with more standard trackpads, using the wheel while pressing the ctrl key. In that case, no origin 🤷‍♂️ you can try with Chrome.

Thanks for the clarification 👍 Would using clientY and clientX as the fallback origin make sense in that case? Because that's what I will be using as the fallback origin in my app. Maybe it makes sense to also provide those as the fallback origin on the `react-use-gesture` level. Let me know what you think.

Thanks for all the insights! All that information is quality content for the documentation!

**Comment by dbismut** [comment]
You're right, I should add this to the doc :) I'll see about mouse coordinates as default.

**Comment by dbismut** [comment]
Hey @n1ru4l type of origin is now defined in `8.0.0-alpha.7` (it actually was defaulted to mouse coordinates in the previous alpha, so I was wrong when I said it was `undefined`).

Regarding casting events to Three, have a look at this: https://github.com/pmndrs/react-use-gesture/issues/182#issuecomment-699669170

Hope that helps ;)

**Comment by n1ru4l** [comment]
It seems like a new alpha is released but the code is not pushed on github yet 😅 (v8.0.0-alpha.9)

**Comment by dbismut** [comment]
v8 is now released
