### ISSUE TITLE
Updating config

### ISSUE THREAD

**Issue by illiaGorbatov** [pmndrs/react-use-gesture#185]
Hi! Is there any method for updating config object without re-render? It seems, like config updated only on rendering, but all my animations works with refs to avoid it.

**Comment by dbismut** [comment]
Hi @Harbatau can you give me your use case? Also, bear in mind that re-rendering is not a bad thing per se. It can become a performance bottleneck if you re-render on every frame / drag event but re-render isn't generally a problem. React is based on declarative rendering and people use React because it re-renders!

**Comment by Harbatau** [comment]
My case is very similar for this https://codesandbox.io/s/fh8r8 with bounds for each draggable element.  I just want to update bounds in config while starting drag another item, but bounds works like this item is first dragged element.

**Comment by dbismut** [comment]
I see. `bounds` could accept a function that would be computed at the start of each gesture (or even on every frame), this can be investigated.

**Comment by Harbatau** [comment]
My config is {filterTaps: true, bounds: getBounds(), rubberband: true}. Function getBounds triggered only on rerender. How to trigger or implement it at the start of each gesture? Сan you explain with a simple example?

**Comment by dbismut** [comment]
I was suggesting an improvement to the existing API, I don’t think this is possible at the moment except if you want to reimplement the bounds feature yourself.

**Comment by Harbatau** [comment]
Aw, sorry, I misunderstood your previous answer. Thank you for fast help!

**Comment by justin-hackin** [comment]
I too am looking for this feature.  My use case is that I'm using the useWheel to zoom in and out an svg image and the amount of scale for the svg is dependent on the window size (which is held in hooks state).  I performed a clamp on the movement y in the event callback but then when you overshoot the bounds, you have to scroll back through the overshoot to get back within the bounds that cause visible change.

**Comment by guglielmodanna** [comment]
> I see. `bounds` could accept a function that would be computed at the start of each gesture (or even on every frame), this can be investigated.

Such feature would be fantastic! I ran into @illiaGorbatov issue as well, and `bounds` being able to accept a function would unlock powerful features with very concise code. Thanks for your guys' work on this amazing library!

**Comment by dbismut** [comment]
Bounds now accepts a function that can depend on state: https://github.com/pmndrs/react-use-gesture/issues/215#issuecomment-715883462
