### ISSUE TITLE
Jerky behaviour with touch drag

### ISSUE THREAD

**Issue by Porges** [pmndrs/react-use-gesture#210]
I’ve been browsing the examples and there seems to be a problem with how touch drag is implemented, I believe due to the mouse-event filtering that the drag recognizer performs. Dragging on a touch screen is very jerky, this might be because of the delay inserted there?

I saw that MDN recommends blocking the mouse events by calling `preventDefault` in the `touchstart` handler. If this was done then probably the filtering would not be required and the problem would go away:

> Applications using Touch events [should] disable the browser handling of gestures by calling `preventDefault()`

A workaround to get correct behaviour is that you can set something like `touch-action: none` when expecting touch drag, but it would be nice if this worked out-of-the-box, as e.g. all the examples don’t have it and behave very jerkily when used with touch.

**Comment by dbismut** [comment]
@Porges I'm not sure what you call jerky. Maybe a screen caption or a video would help? There's a latency in most example which is due to not setting `immediate` to `true` in react-spring but this has nothing to do with the lib.

You don't need to call preventDefault where `touch-action` is set to `none` or if there's no content to scroll.

**Comment by Porges** [comment]
Sorry, I should have been more precise. The jerkiness is that the position doesn’t update frequently enough; unrelated to the latency of springs. Here’s an example video with the pink square example.

First I move with the mouse, then touch (jerky), then add `touch-action:none` and mouse/touch again.

![React Use Gesture Simple - CodeSandbox - Personal - Microsoft_ Edge 2020-09-11 12-40-28](https://user-images.githubusercontent.com/12575/92833581-1dddc400-f42d-11ea-824f-cf99aab50bbd.gif)

**Comment by dbismut** [comment]
Wow that's really weird. `touch-action` is only of use when you use a touch-enabled pointer, which your mouse shouldn't be. I tried on my 2019 MacBook Pro with throttling set to 6x and everything stays smooth.

I just updated the sandbox to the latest versions of react-spring, react-use-gesture and react. Can you try once more? Can you also give me your configuration (browser, OS, hardware)?

**Comment by Porges** [comment]
To be clear I am using touch, not mouse (it's a Surface Book screen).

**Comment by dbismut** [comment]
Hm there's unfortunately no way I can have access to a Surface at this moment. Do you find the same behavior on a regular phone? Can you try updating to v8.0.0@next see if this helps? (v8.0.0 does require `touch-action: none` as it uses pointer events).

**Comment by Porges** [comment]
Did some more tests for touch:

* Surface Book
  * Edge (Edgium): jerky
  * Firefox: smooth

* Android
  * Chrome: jerky
  * Edge: smooth
  * Firefox: smooth

**Comment by dbismut** [comment]
@Porges sorry for not responding earlier, thanks so much for the benchmark. `8.0.0` will require `touch-action: none` to be set since it uses Pointer Events. I'll try to test Android Chrome asap.

**Comment by Schwefelhexa** [comment]
I might be reviving a dead thread here, but I've run into the same issue.
On Chrome and Firefox desktop, the movement was perfectly smooth, but really laggy on Chrome mobile.
I'm running `7.0.16`, but `touch-action: none` has fixed this for me, too.

**Comment by dbismut** [comment]
@Schwefelhexa this can be expected to a certain extent. It is normal that when your drag movement interferes with the browser scrolling something wrong would show. touch-action is made exactly for that purpose and is mentioned in the documentation of this lib.

**Comment by Schwefelhexa** [comment]
@dbismut Thanks, now that I've found it too. But this seems really hidden to me, maybe you might consider mentioning this in `Getting started`?

Either way, thanks for your help!

**Comment by dbismut** [comment]
Indeed you're right. This is something that we should make more obvious. When I revise the doc for v8 I'll try to keep it in mind!

**Comment by Porges** [comment]
Right, all the examples should have it at the very least.

**Comment by dbismut** [comment]
Closing this unless someone thinks this issue persists?
