### ISSUE TITLE
Tarot card example stopped working after version 5.2.4

### ISSUE THREAD

**Issue by riazjahangir** [pmndrs/react-use-gesture#214]
I'm trying to use the form of `useGesture` that looks like:

```
const bind = useGesture(state => {
  console.log('Do something here')
})
```

and am finding that the function never gets called on any gesture. Specifically I'm trying to execute this on hover and drag.

I saw that the Tarot card example uses the same approach, and was surprised to find even that example no longer works.

Version history:
- 5.2.4 - Tarot card example works fine, `useGesture` handler is getting executed
- 6.0.0-beta.1 - `useGesture` handler is still getting executed (though the motion using react-spring@9.0.0-beta.3 looks wrong)
- 6.0.0 - `useGesture` handler is not getting executed

I've forked the Tarot example here: https://codesandbox.io/s/brave-euler-kbtjj?file=/src/index.js
Only changes are:
1. Added a `console.log` statement inside the gesture handler
1. Changed react-use-gesture version to 6.0.0

Note if I use `useDrag` or `useHover` as in:
```
const bind = useDrag(state => {
  console.log('Do something here')
})
```
then the handler does get called and I can see this statement in the console. It's only `useGesture` that has the problem.

**Comment by riazjahangir** [comment]
Well, I just found this in the changelog 😄 

> useGesture doesn't support a function as a shortcut for onDrag. Please use useDrag from now on.

I found the updated example at https://use-gesture.netlify.app/docs/examples. Unfortunately the Tarot example at react-spring (https://www.react-spring.io/docs/hooks/examples) still uses the old `useGesture`, hence my confusion.

Closing!

**Comment by dbismut** [comment]
Sorry for the inconvenience mate. We desperately need to unify all examples under one roof with latest versions of all libs. One day this will happen.
