### ISSUE TITLE
How to use useSprings hooks and reset the initial drag state for multiple items?

### ISSUE THREAD

**Issue by riccardocaranfil** [pmndrs/react-use-gesture#215]
Here is my code, the problem happens when my algorithm changes the coordinates of the points dynamically. With single useSpring I can control this using the `initial` function, but with multiple I can't, any tips?

`const [springs, setSprings] = useSprings<any>(items.length, (index: number) => {
        // Getting right coordinates
        let [x,y] = newPointValues(index)
        return {x,y}
    });

    const [isDragging, setIsDragging] = useState(false)

    const bindDrag = useGesture({
        onDrag: ({dragging, args: [index], movement}) => {
            console.log("[dd] dragging")
            if (itemIndex !== index) {
                // set current item index
                setItemIndex(index);
            }
            
            // Save relative position 
            calcPosition(index, movement)

            setIsDragging(dragging)

            let [mx, my] = movement
            
            setSprings((i: number) => {
                if (index !== i) return
                return {x: mx, y: my}
            })
        }
    }, {
        drag: {
            bounds: relativePos,
            initial: () => {
                // Initial get called before all gesture events, how to get index of right element?
                return (itemIndex !== undefined && newPointValues(itemIndex!!)) || [0, 0]
            }
        },

    })`

An example is available here [https://codesandbox.io/s/react-typescript-forked-zk6wl](https://codesandbox.io/s/react-typescript-forked-zk6wl), as you can see the initial function return the value of the item dragged before

**Comment by velthune** [comment]
You can try saving initial position on hover event:

  ```
 onHover: ({ args: [index] }) => (itemIndex !== index) && setItemIndex(index)
```

**Comment by dbismut** [comment]
I'll leave this open as I'll investigate to possibly make initial accept an argument. Not exactly sure how for now.

**Comment by dbismut** [comment]
@riccardocaranfil this should be now possible in v8 latest beta. Bounds and initial can now be functions of the gesture state, meaning you can do something like you suggested:

```js
bounds: ({ args: [index] }) => ({ left: 100 * index }),
initial: ({ args: [index] }) => [springs[index].x.get(), springs[index].y.get()]
```

**Comment by dbismut** [comment]
Fixed in v8

**Comment by riccardocaranfil** [comment]
@dbismut I'm updating now the code and I'm getting no state in the initial callback
Here my code:

      const bindDrag = useGesture({
        onDragStart: () => {
          ...  
        },
        onDrag: ({args: [index], movement}) => {
            ...
        },
        onDragEnd: ({args: [index], movement}) => {
           ...
        },
    }, {
        drag: {
            bounds: bounds,
            rubberband: true,
            initial: ({args: [index]}) =>  [springs[index].x.get(), springs[index].y.get()]
        },
    })

The problem is that in the `initial` function the state object is  `undefined`

Can you help me?

**Comment by dbismut** [comment]
Can you upgrade to the latest beta v10 `10.0.0-beta.7` ? It is pretty stable and fixes some bugs from v9. The initial prop is replaced by `from` though, and you should use `offset` with it rather than `movement`.

Also, as a side note `useGesture` is a bigger import than `useDrag`. If you just need it for `onDragEnd` or `onDragStart`handler I'd recommend to use `first` and `last` state props.

**Comment by riccardocaranfil** [comment]
@dbismut I updated the library as you suggest and now I can get the index, but not the really first time

        const bindDrag = useDrag(({args: [index], first, last, offset}) => {
          if (first) {
              ....
          } else if (last) {
              ...
          } else {
              ...
          }
      }, {
          ...
          from: ({args}: any) => {
              // {args: [index]} <--- error destructuring cause args is undefined at the begining
              const index = args?.[0] 
              return index !== undefined ? newPointValues(index) : [0,0]
          }
      })

Any other tips?

Thanks

**Comment by dbismut** [comment]
Hi, please provide a sandbox, that would really help.

**Comment by dbismut** [comment]
@riccardocaranfil thanks a lot for raising this, it was indeed a bug. Should be resolved in latest v10 beta.
https://codesandbox.io/s/example-react-use-gesture-issue-forked-q0bui

**Comment by riccardocaranfil** [comment]
@dbismut Thanks for you're suggestions now I have all working fine.

I have only one question: while dragging the dots I notice there is a sort of friction (I've already play a bit with the "friction" property) and the dot doesn't follow the mouse perfectly as I expect, do you know why this happens?

PS. The problem is more visible if you zoom a bit in

**Comment by dbismut** [comment]
@riccardocaranfil this is not related to `@use-gesture`, this has to do with `react-spring`, you should use the `immediate` option if you don't want the trail / spring effect.

Basically you should do this:

```js
set({ x: myXValue, immediate: true })
```

Btw, feel free to upgrade to `@react-spring/web` (latest is v9.2), this will result in a lighter install and less peer dependency warnings!
