### ISSUE TITLE
React-use-gesture domTarget and r3f

### ISSUE THREAD

**Issue by promontis** [pmndrs/react-use-gesture#217]
I've created a sandbox for this problem... https://codesandbox.io/s/react-use-gesture-simple-forked-7wmko?file=/src/index.js

I'm trying to use `domTarget` within react-use-gesture, but it doesn't work. It does work for a button (notice that it doesn't need `.current` for the ref), but not for a r3f primitive. It also works without using `domTarget`, but instead using `{...bind()}`.

AFAIK `domTarget` is of type `EventTarget` and `ReactThreeFiber.Object3DNode` implements `EventTarget` right? In my own software I'm using Typescript and the types seem to match up.

Could you point me into the right direction why this isn't working?

**Comment by dbismut** [comment]
@promontis please use v8 alpha 9 as a bug with multiple refs has been fixed.

**Comment by promontis** [comment]
@dbismut updated to v8 alpha 9, but problem seem to remain

**Comment by dbismut** [comment]
Yep that's expected.

**Comment by dbismut** [comment]
I'm leaning to closing this as supporting refs beyond HTML elements is currently beyond the scope of this lib. @drcmda I don't see how to solve this, I guess it should be on react-three-fiber's side to emulate the behaviour of a HTMLElement ref somehow?

**Comment by promontis** [comment]
I've fixed it by not using domTarget, but instead I pass the target as children props. Then, I wrap the children with a `<group {...bind()}>`

**Comment by Nearoo** [comment]
@promontis Sorry, could you elaborate on how you worked around the problem? Thanks!

**Comment by promontis** [comment]
If I recall correctly, you can't use domTarget. You can however...
- pass the children to a component 
- use a `group` so that you can bind and implement the gesture logic there
- render the children within that `group`

**Comment by Nearoo** [comment]
Ah, I get your point - sadly doesn't help my problem, I'm trying to attach the listener via `target`, without `bind()`. Thanks anyway!

**Comment by promontis** [comment]
@Nearoo ja `target` didn't work for me. And it is outside the scope of this project to make it work with r3f, so that's why I used `bind()`. Good luck :)
