### ISSUE TITLE
Page unresponsive for one click after a swipe

### ISSUE THREAD

**Issue by apostolos** [pmndrs/react-use-gesture#218]
So, there is a weird bug that happens after doing a quick touch drag gesture. The next click/tap anywhere on the page or on the drag target itself is ignored.

It looks to me like an event handler is not cleaned up properly after a `swipe` gesture is recognized, but I might be wrong. I can't reproduce it when doing the gesture more slowly.

Important detail: it only happens with touch. Can't reproduce it on desktop (mouse).

The bug can be easily reproduced on the [threshold](https://github.com/pmndrs/react-use-gesture/tree/v8/examples/src/threshold) example (v8 branch).

Repro video: https://www.youtube.com/watch?v=azL9lYOngFU
_(explainer: the click on the back button after the second gesture is ignored)_

Bug reproduced in:
- Chrome desktop, mobile/touch simulation
- Chrome Android
- Edge desktop, mobile/touch simulation
- Edge Android

Bug not reproducing in:
- Firefox (desktop or mobile)
- iOS 14 (via browserstack)

Tested on:
- v8 alpha.8
- v8 alpha.10

**Comment by dbismut** [comment]
That's weird, I can't reproduce on my Macbook using Chrome in touch mode. Is there anything showing in the console? Are you able to inspect the elements with the Chrome inspector?

**Comment by apostolos** [comment]
Nothing on the console. I do have access to the Chrome inspector.

I tried on macOS via Browserstack and I **cannot** reproduce it there either. However it does reproduce on a Linux (Ubuntu) laptop on Chrome, although not as often and reliably as on Windows or Android. It usually takes a few tries to manifest.

I will have access to a physical Macbook later tonight and test again.

On Android it happens almost every time (`Android 11`; `Chrome 86.0.4240.99`). Reproduced here as well: https://www.lwjgl.org/
(tap to open the main menu, swipe fast to close, then try tapping on the menu again).

**Comment by dbismut** [comment]
Doesn't work on my iPhone! Will try on a PC tomorrow.

**Comment by dbismut** [comment]
I'm testing on a PC and I really can't reproduce in touch mode... Using Chrome 86.0.4240.75.

**Comment by apostolos** [comment]
Recorded two videos on Android with "Show touch operations" enabled:

1. [Threshold example](https://github.com/pmndrs/react-use-gesture/tree/v8/examples/src/threshold) repro:
https://www.youtube.com/watch?v=IrQ9wXDHjUA
2. [LWJGL](https://github.com/LWJGL/lwjgl3-www/blob/master/client/containers/Sidebar.tsx) repro:
https://www.youtube.com/watch?v=3C7dAcJ96_A

**Comment by apostolos** [comment]
Also confirmed that it does NOT happen on `macOS` (Safari or Chrome) and it does NOT happen on `iOS`.

Reproduced on multiple `Windows` and `Android` phones (Chrome).

Unless there is something obviously wrong with the code, this is starting to look like a browser bug to me... 🤒

**Comment by dbismut** [comment]
That's really weird. Let's keep this open and see if someone reproduces.

**Comment by apostolos** [comment]
I finally managed to isolate the problem. It is caused by `touch-action` and it happens exclusively on Chrome (Windows, Android, and less so on Linux).

Setting anything other than `touch-action: auto` or `touch-action: manipulation` causes the problem to manifest. I can reproduce it on any page and on any element. Of course, it has nothing to do with `react-use-gesture`, so sorry for wasting your time.

I opened an issue on Chromium's tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1141207

**Comment by dbismut** [comment]
Glad you nailed that one!

**Comment by apostolos** [comment]
Hi @dbismut,

FYI the issue was just accepted by Chromium

**Comment by dbismut** [comment]
Oh wow congrats!

**Comment by apostolos** [comment]
@Linksku unfortunately, no. It's still broken and the bug is still unassigned:
https://bugs.chromium.org/p/chromium/issues/detail?id=1141207

There is something fundamentally broken in Blink's input handling (on Android & Windows), I doubt a workaround is possible on this one. It looks to me as some system-level gesture detection logic is breaking/taking over the event handling.

**Comment by Linksku** [comment]
After several hours, this solution seems to work:

```
let timer: number | null = null;
window.addEventListener('touchend', event => {
  if (timer) {
    clearTimeout(timer);
  }
  timer = window.setTimeout(() => {
    event.target?.dispatchEvent(new Event('click', {
      bubbles: true,
      cancelable: true,
    }));
  }, 0);
});

window.addEventListener('click', () => {
  if (timer) {
    clearTimeout(timer);
  }
});
```

I haven't fully tested it, but it never triggered `click` unexpectedly.

**Comment by Emiliano-Bucci** [comment]
@Linksku Hi! After tons of hours I finally found a solution to this odd bug! Question: would be necessary to clean up both listeners somehow?

**Comment by msgoloborodov** [comment]
The solution is calling `event.preventDefault()` on `touchmove` event on element.

I think that Chrome starts flying scrolling after fast swipe, and click is ignored while scrolling in progress (about 2 seconds).
