### ISSUE TITLE
useDrag and OrbitControls don't work well together

### ISSUE THREAD

**Issue by ikteru** [pmndrs/react-use-gesture#221]
I'm trying to get useDrag and OrbitControls to play well together, but it's not working. 
The scenario I'm trying to achieve is to be able to drag an three js object using useDrag and at the same time be able to use OrbitControls. All of this while using react-three-fiber.  
The codesandbox is the following: https://codesandbox.io/s/react-three-fiber-gestures-forked-lpfv3?file=/src/App.js:1099-1127

The behavior I want : When I drag the object, I don't want the orbit camera to change. I want the object alone to be dragged.

The actual behavior: When I drag the object, it doesn't get dragged, the camera is the one that moves.

**Comment by dbismut** [comment]
This seems to work:

```jsx
<orbitControls args={[camera, gl.domElement]} ref={orbitRef} enableRotate={!dragging} />
```

But I'm not an expert in THREE nor r3f. @drcmda maybe there's a better way without using state? I thought `event.stopPropagation()` would work but it doesn't...

**Comment by ikteru** [comment]
Thanks, that did help. I tried using the "enabled" property, but it didn't work. Didn't know about the "enableRotate" one. @dbismut , any ideas on how to make the dragging behavior better? 
Right now, when I drag, it's kinda slow, so the mouse and the object are far from each other. How do I make it faster and make the ball actually follow the mouse and stick to it?

**Comment by ikteru** [comment]
Actually, on some more testing, it doesn't work right away. You have to manually set enableRotate to false first, then later assign it !dragging for it to work. If you just start from scratch with enableRotate={!dragging} it's not going to work. That's some really work behavior.

**Comment by dbismut** [comment]
@ikteru Please use the discord channel if you need specific help. Closing as not an issue with the lib.
