### ISSUE TITLE
Help/input wanted: usePinch with overflow:auto and native-scrollbars

### ISSUE THREAD

**Issue by richarddd** [pmndrs/react-use-gesture#222]
First of all, thanks for an awesome library 🥳

I have this slider with content covering more than the screen, and my intention was to use this lib to create a pinch+zoom effect leveraging the native scrollbars inside a div with auto overflow.

I have been struggling now for some time getting this to work and so far it works OK on desktop
https://codesandbox.io/s/pinch-zoom-slider-34eby

However, there are still two major issues happening:

1. There is a slight delay when pinching. I suspect this has to do with onPinchStart.
2. When pinching rapidly (without waiting for the spring to catch up) there is flickering and the content goes all over the place
3. Origin when using pinch-to-zoom on mobile doesn't seem to act the same way as when using my trackpad. Its slightly off.

I'm sure you guys are super busy, but I would love it if someone could take a look at what I'm trying to accomplish. Maybe this is something that also could be showcased in a demo of use-gesture/use-spring? :)

Thanks in advance!

**Comment by dbismut** [comment]
Seems to be working pretty decently on my iPhone, what are you testing on?
Origin should be the cursor origin on desktop, on mobile it's the centre of the two touch points.

**Comment by richarddd** [comment]
> he cursor origin on desktop, on m

Testing on Android and iPhone. The issue is mainly if you pinch and then quickly pinches again. I'm also sure there is a cleaner way of dealing with the translation => scrollLeft & scrollTop rather than persisting the scrollLeft/top and try to reverse that when another pinch occurs. @dbismut correct me if I'm wrong but is pinch-start determined using timers? AFAIK there is no "native" event for pinch stop and start

**Comment by dbismut** [comment]
Pinch should start as soon as two fingers touch the screen, there's no timer. I'll have a look at the code when I can.

**Comment by dbismut** [comment]
Hey @richarddd I'm sorry I didn't have time to look, I've been busy with other things and that problem isn't easy. Did you come up with something viable?

**Comment by richarddd** [comment]
> Hey @richarddd I'm sorry I didn't have time to look, I've been busy with other things and that problem isn't easy. Did you come up with something viable?

Hi @dbismut no worries :) I ended up using another approach which worked using transformation origins instead and ditched this :)

**Comment by VillePakarinen** [comment]
> I ended up using another approach which worked using transformation origins instead and ditched this :)

Hey, @richarddd, any chance you could share a codesandbox of what you ended up doing?
