### ISSUE TITLE
Unexpected Drag Offsets in SVG

### ISSUE THREAD

**Issue by amcdnl** [pmndrs/react-use-gesture#223]
I'm trying to use the drag gesture to draw a SVG path element using the start position on mouse down and the end position of cursor location. Problem is the offsets are wonky. In the below image, I have a arrow to where started dragging but you can see the arrow in grey is no where near that start location.

![image](https://user-images.githubusercontent.com/227909/98160225-debb7480-1eab-11eb-8540-fc3fd86d819b.png)

Furthermore if come back and drag again, its even further off. I'm presuming its picking back up its previous location? The code is pretty simple:

```
  const bind = useGesture({
    onDrag: (event) => {
      console.log('drag', event);
      onDrag(event, properties);
    },
    onMouseDown: (event: any) => {
      onDragStart(event, properties);
    },
    onDragEnd: (event) => {
      onDragEnd(event, properties);
    }
  }, {
    drag: {
      enabled: !disabled,
      threshold: 10
    }
  });
```

and then it just takes that those coordinates from the `offset` and maps them to start points:

```
const onDrag = (event) => {
    const [x, y] = event.offset;
    const endPoint = { x, y };

    setDragCoords([
      {
        startPoint: dragCoords?.[0]?.startPoint || endPoint,
        endPoint
      }
    ]);
  };
```

which is read by the line here:

```
const d = useMemo(() => {
    const points: any[] = sections
      ? [
        sections[0].startPoint,
        ...(sections[0].bendPoints || []),
        sections[0].endPoint
      ]
      : [];

    const pathFn = line()
      .x((d: any) => d.x)
      .y((d: any) => d.y)
      .curve(curveBundle.beta(1));

    return pathFn(points);
  }, [sections]);
```

You can see a demo of this behavior here: https://reaflow.dev/?path=/story/canvas--simple

The relevant source code in the project is here:
- Drag Start - https://github.com/reaviz/reaflow/blob/master/src/symbols/Node/Node.tsx#L81-L98
- Drag Mapping - https://github.com/reaviz/reaflow/blob/master/src/utils/useDrag.ts#L12-L22
- Line Render - https://github.com/reaviz/reaflow/blob/master/src/Canvas.tsx#L151-L157

**Comment by dbismut** [comment]
I'll have a look but top of my head, just reading your gesture code, here's a few things. 

1. There's no reason this lib would fail on SVG more than on any other elements. This lib is just a thin layer of logic on top of React Synthetic events or native events. 

2. If you're using v8, you can rely on the useDrag hook only, with triggerAllEvents config attribute set to true and the intentional flag combined.

**Comment by amcdnl** [comment]
@dbismut - Ya, I think its just something I'm doing wrong but you never know. Would love any feedback you have.

**Comment by amcdnl** [comment]
OK - I think I figured it out - I need to use `movement` rather than `offset`. Additionally I need to calculate the `movement` against the `x`/`y` of the `rect`.

```
    onDrag: ({ movement, ...rest }) => {
      onDrag({
        ...rest,
        offset: [movement[0] + x, movement[1] + y]
      }, properties);
    },
```

**Comment by dbismut** [comment]
It's been a pretty busy week at work so I didn't have time to check yet but did you have a look at the initial option?

**Comment by amcdnl** [comment]
Ya - setting initial didn't seem to help. Perhaps you might be able to look at it? The code is open-source.

**Comment by dbismut** [comment]
I'm on it but I'd like to discuss it with you first. Can you join the discord and ping me in the right channel?
