### ISSUE TITLE
Initial gesture option with useGesture hook

### ISSUE THREAD

**Issue by Cstrachan4** [pmndrs/react-use-gesture#225]
Currently trying to build a multiple gesture card slider that is both draggable and scrollable within certain bounds (and with rubberbanding).

Working fine when I use just a single gesture like below

```
const [{ x }, set] = useSpring(() => ({ x: 0 }));
const bind = useDrag(
    ({ down, offset: [ox] }) => {
      set({x: ox,immediate: down})
    },
    { initial: () => [x], bounds: { left: -TOTAL_WIDTH, right: 0  }, rubberband: 0.3 }
)
```

But when I try to achieve the same with the useGesture hook instead of one of the single gesture one – the bounding / rubberband doesn't work. Maybe the below is wrong? Couldn't find a combination of these in the documentation anywhere, apologies.

```
const [{ x }, set] = useSpring(() => ({ x: 0 }));
const bind = useGesture(
    {
      onDrag: ({ down, offset: [ox] }) => {
        set({x: ox, immediate: down})
      }
    },
    {initial: () => [x], bounds: { left: -TOTAL_WIDTH, right: 0  }, rubberband: 0.3}
);
```

**Comment by dbismut** [comment]
When you use useGesture you must wrap gesture options with the gesture key.

So config should look like:

```js
{ domTarget, drag: { ...dragOptions }
```

https://use-gesture.netlify.app/docs/options/#structure-of-the-config-object

**Comment by Cstrachan4** [comment]
Sorry completely missed that in the docs and in all my searches. Thanks for the tip!

**Comment by dbismut** [comment]
That's fine. Not the most intuitive part of the api I must say. If you have a better way to phrase this in the docs let me know!
