### ISSUE TITLE
Pinch origin "undefined" in Safari

### ISSUE THREAD

**Issue by richarddd** [pmndrs/react-use-gesture#226]
`origin` value of pinch gesture returns `undefined` for Safari

Check log of pinch here:
https://codesandbox.io/s/sk5bf

**Comment by dbismut** [comment]
I guess I'll start setting a template for issues 😂

Make sure you're using the latest version of the lib and explicit which version of Safari and hardware you're using.

**Comment by richarddd** [comment]
@dbismut sorry about that 🤓

I'm using 8.0.0 and Safari 14.0 (14610.1.28.1.9)

**Comment by dbismut** [comment]
Thanks for reporting this! Should be fixed in 8.0.1. Note that I'm using `clientX / clientY` for consistency, so maybe origin is not what you need if you want the position of the mouse relative to the page.
