### ISSUE TITLE
missing r3f metadata with onDrag gesture

### ISSUE THREAD

**Issue by goldbuick** [pmndrs/react-use-gesture#227]
https://codesandbox.io/s/usedrag-example-puxsq

we get the r3f event metadata on the initial events, but subsequent events it is missing.

**Comment by dbismut** [comment]
Hi @goldbuick thanks again for reporting this! Will be fixed in `8.1.x`, which you can test in an alpha version using the next tag:

```
yarn add react-use-gesture@next
```
