### ISSUE TITLE
Any reason to set "memo" to undefined on new event?

### ISSUE THREAD

**Issue by ruifortes** [pmndrs/react-use-gesture#230]
Hi! Thanks for the great lib and...here's a somewhat irrelevant question :-P

I'm using some intermediate values in a useDrag handler but have to recalculate them from component state on the event start.

Is there a reason not to keep previous memo?

**Comment by dbismut** [comment]
Not sure I understand the question? Do you want to know why memo is reset at the start of each gesture?
