### ISSUE TITLE
useDrag doesn't work in mobile

### ISSUE THREAD

**Issue by Zaynex** [pmndrs/react-use-gesture#232]
codesandbox

https://codesandbox.io/s/action-sheet-forked-p7prx?fontsize=14&hidenavigation=1&theme=dark

Select mobile mode in browser.

Can't drag smooth, it's strange.

**Comment by Zaynex** [comment]
in codesandbox, it can toggle preview mode.
But use dev-tools，it can't work.  I will continue to observe it

**Comment by Zaynex** [comment]
see this link in your mobile phone (like safari)
https://p7prx.csb.app/

**Comment by Zaynex** [comment]
After some investigation, set `touch-action: none` will help.
The device will trigger `onpointercancel` event and then transfer to `onDragEnd`. 
If you want custom control drag drop, use `touch-action: none` for the DOM.

**Comment by dbismut** [comment]
After some investigation like reading the docs maybe 😏?
There are two things that feel wrong with your sandbox.

1. Not sure what `useState` does?
2. Setting the `top` and `left` attributes are not the best way to move DOM elements as you don't benefit from hardware acceleration like when you're using `transforms`.
3. `onPointerUp` and `onPointerCancel` will mess up with `{...bind()}` as explained in the docs: https://use-gesture.netlify.app/docs/hooks/#native-react-event-handlers
4. There's nothing wrong in using `initialPosition` the way you do but you might want to have a look at the `initial` option.

**Comment by Zaynex** [comment]
1. I thought it was I change `left` and `top` that cause the element can't drag. So I change the postion by dom reference.
As you can see, I annotated the `set` function from `useState`.

2. Yes.But my real production is complex, I will try to use `transform`.

Thanks, I should read the documentation more carefully  -)
