### ISSUE TITLE
v8.1 drag automatic interrupt

### ISSUE THREAD

**Issue by Iixianjie** [pmndrs/react-use-gesture#235]
**reproduce**
1.open in chrome phone mode
<https://15qb9.csb.app/>

2.drag the red box and look at the console

3. drag stopped after a few triggers

4.it works on pc

**code**
<https://codesandbox.io/s/busy-gagarin-15qb9?file=/src/App.js>

**Comment by dbismut** [comment]
You need to set `touch-action: none|pan-y|pan-x` depending on your usecase as mentioned in the docs repeatedly.
