### ISSUE TITLE
Firefox wheel distance is not in pixel

### ISSUE THREAD

**Issue by paradoxxxzero** [pmndrs/react-use-gesture#236]
This example https://codesandbox.io/s/nigoy works fine in chrome but in firefox it takes forever to scroll.

Apparently chrome use a pixel [deltaMode](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode) and firefox a line deltaMode : https://bugzilla.mozilla.org/show_bug.cgi?id=1392460

It would be great to take that in account

**Comment by dbismut** [comment]
Hm... On my Macbook Firefox seems to behave decently... What's the course of actions you would recommend?

**Comment by paradoxxxzero** [comment]
What's your `event.deltaMode`?

I would recommend to normalize the `deltaX` and `deltaY` according to `event.deltaMode` like they did here for instance: https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js#L144-L155

**Comment by dbismut** [comment]
It's says `0` when I log `event.deltaMode` on Firefox. Ok I'll just rip off the link you've sent I guess ;)

**Comment by dbismut** [comment]
@paradoxxxzero can you try `8.1.0-beta.4`? Essentially I just implemented the constants from the link you've sent, nothing more at this point.

Here is the commit:
https://github.com/pmndrs/react-use-gesture/commit/972cd95055729182730438af5dcbb51a9ad38b4c

**Comment by paradoxxxzero** [comment]
It works ! However 40 is a bit much for my setup, so I investigated how to determine the LINE_HEIGHT and well: https://stackoverflow.com/questions/20110224/what-is-the-height-of-a-line-in-a-wheel-event-deltamode-dom-delta-line (on my linux laptop the `getScrollLineHeight()` reports 19)

I don't know if it's necessary to go the way of creating hidden iframes for this, in any case it now scrolls on firefox so even without an accurate line height it's still an improvement.

**Comment by dbismut** [comment]
Hi @paradoxxxzero indeed that would be silly for the purpose of this lib, and I think it's rather up to FF to try to align with other browsers :) Thanks for reporting this though!
