### ISSUE TITLE
[beta] re-shuffeling of dom nodes during drag no longer works

### ISSUE THREAD

**Issue by freund17** [pmndrs/react-use-gesture#242]
**Describe the bug**

Since v8.1.0-alpha.1 reshuffeling dom-nodes during a drag no longer works.

I guess, this is a niche problem and my use-case might be contrived... And it is probably better praxis to use z-index to keep the active item in the foreground instead of reordering the dom-tree...

But it worked in v8.0.1 so... hey, here is an issue. 😅 

**Sandbox or Video**

https://codesandbox.io/s/reverent-driscoll-j88xx

1. Drag the right box -> works
2. Drag the left box -> breaks, when cursor no longer inside box

**Information:**

 - React Use Gesture version: since v8.1.0-alpha.1; (still broken on v8.1.0-beta.6)
 - Device: Desktop Computer 🙃
 - OS: Windows 10
 - Browser: Chrome 87

**Checklist:**

  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `pointer-events: none` to the draggable element. (Why would that help? Did you mean `touch-action: none;`?)

**Comment by dbismut** [comment]
Lol i need some sleep, I'll correct the template issue now for a start.

**Comment by dbismut** [comment]
This is indeed pretty contrived. I'm not sure what's happening internally but for sure, `setPointerCapture` seems to be a dealbreaker for your usecase. I can conceive a scenario where that might be useful (let's say that you need a page transition to happen mid-drag, your dragged element would probably unmount), but I don't think I'll go back to earlier implementations without `setPointerCapture`, which is actually helpful for more common scenarios.

Is there another way to achieve what you were doing? Or can you elaborate a more tangible usecase that we could try to solve?

**Comment by freund17** [comment]
> Is there another way to achieve what you were doing?

[Yes](https://codesandbox.io/s/romantic-mirzakhani-9ugi8)
I did not try with my *real* application, but I have no reason to think that it wouldn't work there.

> Or can you elaborate a more tangible usecase that we could try to solve?

No
You'll hear from me, if I run into one. 😉 
Reordering list elements, maybe? 🤷 

Btw: I agree with the `wontfix`. Just wanted to let you know that something broke. :+1:

**Comment by dbismut** [comment]
Indeed, that's good to know, I hadn't thought about this! I'll close it but feel free to comment if you want to push this discussion further.
