### ISSUE TITLE
useGesture doesn't work on iOS(13.0)  

### ISSUE THREAD

**Issue by Zaynex** [pmndrs/react-use-gesture#243]
**Describe the bug**
> A clear and concise description of what the bug is.

useGesture doesn't work on iOS(13.0)  .
Just use the offical demo link, and open with safari (or chrome mobile)

**Sandbox or Video**
> If applicable, please provide a minimal reproduction sandbox on code sandbox. Or a video / screenshots that could help.

https://codesandbox.io/s/multi-gesture-card-forked-rk7ff?file=/src/index.js 
(just add touch-action from `multi-gesture-card`)

**Information:**
 - React Use Gesture version: [v8.1.0-beta.6]
 - Device: [iPhoneX]
 - OS: [iOS13.0]
 - Browser [safari, chrome]

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

I feel 😭, hope to make progress asap.

**Comment by dbismut** [comment]
@Zaynex please feel the information properly in the template issue, these things are here for a reason.
Can you also please try this sandbox: https://codesandbox.io/s/multi-gesture-card-forked-rk7ff?file=/src/index.js

If this is specific to 13.0 I have no means of testing it since I upgraded to iOS 14.

**Comment by Zaynex** [comment]
What is difference about your sandbox ? It seems just copy my link . Do you fork my sandbox ?

**Comment by dbismut** [comment]
lol wrong link sorry, I've updated my comment above.

**Comment by Zaynex** [comment]
If this is offical sandbox in readme，I haved tried. It can't work.Because the offical sandbox can't work, I have to add `touch-action` to avoid accidents.

**Comment by dbismut** [comment]
Can you please try? If I'm asking that's for a reason.

That sandbox already has touch-action set to none so I'm not sure what the problem is really. 

Saying "xxx doesn't work" without further description is not helping to be honest.

**Comment by Zaynex** [comment]
I also tried it with different device(iOS 10.3.2).
In iOS 10.3.2, `onPointerDown` doesn't support in current version. We should list compatibility.
For example, I searched [can-i-use-onPointerDown](https://caniuse.com/?search=onPointerDown)

API (`onPointerDown`, `onPointerMove`, `onPointerUp`, etc)Compatibility problem is my preliminary judgment.

The insurance scheme is that we use `onMouseDown` ,`onMouseMove` and `onMouseUp`.  I need to migrate my code first.

Thanks for your patience. 
It's a big and excellent  library. I'd appreciate If any guys have the iOS device(iOS10~iOS13.0) and want patch compatibility

**Comment by dbismut** [comment]
Hi, you should look at using https://caniuse.com/pointer, not `onPointerDown` which we are not using. The coverage should be much better (92%). 

There are two immediate options:

- using a polyfill library for Pointer Events such as https://github.com/jquery/PEP
- use react-use-gesture v7.

**Comment by Zaynex** [comment]
Hey, I'm ready to fallback to the v7, thanks.
Don't kid me...
https://github.com/pmndrs/react-use-gesture/blob/c79296734f09a605f825bb502e6bfc2fb2ba2448/src/recognizers/DragRecognizer.ts#L171

**Comment by dbismut** [comment]
I'm not sure where I'm kidding anyone here to be honest...

**Comment by Zaynex** [comment]
Maybe I'm misunderstanding,forgive me.

**Comment by dbismut** [comment]
No worries. I'd still be interested to know if polyfills fixes your issue.

In case I wasn't clear: we're not using `onpointerdown`. We're using `addEventListener("pointer down")` which I guess is what React is doing when passing `onPointerDown` as a prop.

**Comment by Zaynex** [comment]
I create the minimal demo using react-use-gesture v7, it can drag in iOS10.  I'm waiting for the Testers feeback.

I thought the `onDragStart` didn't happen because of  the device didn't suport `onPointerDown`.
So I just tested with the code in iOS10

```
function Card() {
  const domTarget = React.useRef(null)
  React.useEffect(() => {
    domTarget.current.addEventListener("pointerdown", () => {
      console.log("pointerDown")
    })
  }, [])
  return (<div ref={domTarget} style={{width: 100, height: 100, background: 'red', touchAction: "none"}} onPointerDown={() => console.log("down")}></div>)
}
ReactDOM.render(<Card />, document.getElementById('root'))
```

in safari, it will not console any logs.

**Comment by dbismut** [comment]
Did you try the PointerEvent polyfill? What's the OS share of iOS10 btw?

**Comment by Zaynex** [comment]
In order to satisfy your curiosity, I have deliberately tried.
```
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>PEP (Pointer Events Polyfill)</title>
  <meta name="viewport" content="width=device-width">
  <!-- include PEP -->
  <script src="https://code.jquery.com/pep/0.4.3/pep.js"></script>
</head>
<body>
<button id="b" touch-action="none">Test button!</button>
<p><output id="o"></output></p>
<script>
document.getElementById( "b" ).addEventListener( "pointerdown", function( e ) {
  document.getElementById( "o" ).innerHTML = "that was a " +
    e.pointerType + " " + e.type + " on a "+ e.target.nodeName;
} );
</script>
</body>
</html>
```

The offical demo can work.
It also can work in react event
```
<button onPointerDown={/***/}></button>
```

But, when I replace the button element with div. It's fail.
```
//  doesn't work
<div id="aa" onPointerDown={/***/}></div>
```

```
//  doesn't work
document.getElementById('aa').addEventListener('pointerdown',  () => {
})
```

even I add `touch-action: none`, still doesn't work.
