### ISSUE TITLE
capture option seems ignored

### ISSUE THREAD

**Issue by jrmi** [pmndrs/react-use-gesture#245]
When using `{capture: false}` event option, setCapture still seems to be called. This problems is annoying when testing with cypress and sending pointerevent, setcapture not working as pointerId are not really registered by browser.

**Information:**
 - React Use Gesture version: 8.1.0-beta.9
 - Device: PC
 - OS: Linux ubuntu
 - Browser: Chrome (through cypress)

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).

**Comment by dbismut** [comment]
capture is not related to pointer capture, but to event capture as in event bubbling.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

I'm sorry that this doesn't work with Cypress, I had myself to patch testing library to make it work.

**Comment by dbismut** [comment]
Just wanted to add that in any case the lib uses pointerId not just for pointer capturing but also to make sure that the dragged element only reacts to a pointermove event matching the pointerId that initiated the gesture.

**Comment by jrmi** [comment]
> capture is not related to pointer capture, but to event capture as in event bubbling.

Oh I see, my bad, sorry.
