### ISSUE TITLE
Clunky gestures

### ISSUE THREAD

**Issue by zRelux** [pmndrs/react-use-gesture#251]
**Describe the bug**
Am I doing something wrong or are the gestures a bit laggy all I want to do is resize and rotate.

**Sandbox or Video**
https://codesandbox.io/s/admiring-rain-1d4yp

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
I moved this question to the discussion https://github.com/pmndrs/react-use-gesture/discussions/250 here. Please follow up there as it’s not a bug but a misuse of the lib.

**Comment by zRelux** [comment]
I would like to apologise for making the issue twice... I didn't get for the other notification
