### ISSUE TITLE
dragging stops when dragging images

### ISSUE THREAD

**Issue by jrydberg** [pmndrs/react-use-gesture#254]
**Describe the bug**

Trying out useGeasure - seems super-useful, but I ran into what to me feels odd.  I hooked up a drag-geature to an element that has an image as child. When I start draggiing, the drag stops after a few movements. onDragEnd is also triggered. 

I the draggable do not have an image as a child, i do not see this behaviour. 

Is this expected?

**Sandbox or Video**
https://codesandbox.io/s/elated-lalande-udmot
> If applicable, please provide a minimal reproduction sandbox on code sandbox. Or a video / screenshots that could help.

**Information:**
 - React Use Gesture version: v9.0.0
 - OS: macOs
 - Browser: Brave

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hi, this has been a recurring question so I've just added a section in the docs FAQ:
https://use-gesture.netlify.app/docs/faq/#why-cant-i-properly-drag-an-image-or-a-link

Hope it helps.
