### ISSUE TITLE
Origin correction logic for pinch only works on zoom in, not zoom out

### ISSUE THREAD

**Issue by samselikoff** [pmndrs/react-use-gesture#255]
Hey David – thanks so much for your work on this library & also for chiming in on my video!

I copied [your solution](https://codesandbox.io/s/boring-hertz-sokxs) into my project and it's almost all working great, with the exception of zooming out.

Here's a sandbox and video of what I'm seeing:
https://codesandbox.io/s/modern-dew-sfjr8?file=/src/index.js

https://user-images.githubusercontent.com/2922250/105407341-97679900-5bfb-11eb-94ea-f232eaef513a.mov

As you can see, zooming out preserves the origin-correction behavior of zooming in, as long as I start zooming out before the original pinch gesture ends. If I stop after zooming in, then start a new zoom-out pinch gesture, the origin calculation is off.

I noticed in your solution, pinching out to zoom out works correctly regardless if you pause and start a new gesture or not: https://codesandbox.io/s/boring-hertz-sokxs

I simplified out a few things from your example to mine but couldn't see anything that would affect the correction calculation, so any pointers in the right direction would be much appreciated!

**Information:**
 - React Use Gesture version: v9.0.0
 - Device: Mac[e.g. iPhone6]
 - Browser: Chrome and Safari

**Comment by samselikoff** [comment]
The only thing I can really see that's different between the two examples are that you're using React Spring, where I'm just using React state. I'm guessing it has to do with something around the `memo` side or maybe `style.scale.get()` side? Where my example is using a stale value somehow? Or it re-renders because I'm calling setState whereas yours never re-renders?

**Comment by dbismut** [comment]
Hey Sam, good to have you here :)

I've forked my sandbox to use state and indeed it breaks: setting bounds as a function is a new feature is v9 and I guess rerendering messes up with it.

https://codesandbox.io/s/serverless-silence-huvmi?file=/src/index.js

I'll be working on this tomorrow.

**Comment by dbismut** [comment]
Hi Sam, good to have you here :) Sorry if you've seen a deleted post in the meantime, actually it was a stupid mistake in my sandbox and that invalidated my message.

Here's a sandbox using react-spring with an image to better assess the focus point: https://codesandbox.io/s/oj203
Here's the same sandbox using state: https://codesandbox.io/s/huvmi

Both seem to be working fine (minus the smoothness maybe), so I don't think re-renders are the culprit here (you should avoid them anyway but I suppose you'll be using framer-motion at some point hehe).

At the moment your sandbox doesn't zoom in correctly on the first gesture, so there must be something wrong here? Maybe the aspect ratio comes into play somehow?

I'll have a closer look tomorrow.

Nice picture btw.

**Comment by samselikoff** [comment]
> your sandbox doesn't zoom in correctly on the first gesture

Hmm. Are you not seeing the same behavior as in the video I posted?

When I pinch to zoom in, it works for me. I'm using a trackpad on a mac.

> I'll have a closer look tomorrow.

👍

> Nice picture btw

What can I say – I like popcorn! 😄 🍿

**Comment by samselikoff** [comment]
I believe I've tracked it down to the fact that I'm adjusting `left` and you're using `translate3d`.

**Comment by dbismut** [comment]
Hm that's a strong possibility, any reason why you need to use left?

I was using the iPhone simulator on my Mac and for some reason zooming in panned the image to the far right.

**Comment by samselikoff** [comment]
Whoops, wasn't about `left` – it's actually due to the presence of this extra `pinch` option on `useGesture`:

```js
pinch: {
  distanceBounds: { min: 0 },
}
```

I forked your first example and added it, and you can see the same behavior:

https://codesandbox.io/s/relaxed-microservice-zxxim?file=/src/index.js

**Comment by samselikoff** [comment]
Ok – we figured it out!

I thought it was a bug, but what was happening was because distanceBounds had a min of 0, and we were using both `movement` and `offset` in the calculation, but `movement` was being floored to 0 in subsequent gestures, the calculation for the X and Y adjustments was wrong.

I updated my logic to only use offset, and I just put the starting distance into the memo on the first run so I can derive `movement` myself. Mostly have it working now!

**Comment by samselikoff** [comment]
It would be awesome if there was an option to clamp only offset, instead of both offset and movement!

**Comment by dbismut** [comment]
Oh I'm happy you sorted things out! Indeed that's the only case where I happened to be using both offset and movement at the same time. There is one undocumented variable that the lib uses for inner math which is `_movement` and which shouldn't be clamped. It's just the raw movement so it doesn't take `initial` / `bounds` / `threshold` options into consideration.

**Comment by samselikoff** [comment]
@dbismut no worries + makes sense!

Feel free to ignore this, but I was wondering if you could help me understand the logic from your codebox... I kinda sorta get it but when I practice explaining it for my video I find I can't quite make everything out.

I was trying to draw a pic in Excalidraw but I'm still not quite grasping it.

Could you describe to me how you arrived at the code + what each part is responsible for? It looks like you calculate a transformed x, taking into account the distance between the origin of the pinch's gesture and the center of the pic, and then scale it. But again that's about as specific as I'm able to get. I can't quite build it up from scratch in an easily understandable way.

Any tips would be greatly appreciated!

**Comment by dbismut** [comment]
Sure. TBH, this was a bit of trial and error until something worked. But the gist of it was after drawing on paper so I guess I can make a sketch tomorrow, it's pretty late down here 😅

**Comment by dbismut** [comment]
Hi @samselikoff here's an Excalidraw that should help: https://excalidraw.com/#json=6595283790069760,KAC8UfbbUkGDMrpr0QqJTQ

I didn't get into details with `memo` but I guess you're already familiar with how it works! Good luck with explaining this in a video though ^^

**Comment by samselikoff** [comment]
This is amazing. Thank you so very much for taking the time to put this together!

I do understand memo and think this will be enough to get me there... I'll report back if I run into anything else. Thanks again David!!

**Comment by samselikoff** [comment]
Working through this a bit at a time... it's tough to explain it because I'm trying to show it working at each step of the way.

First question:

![image](https://user-images.githubusercontent.com/2922250/106193294-4fa4bc80-617b-11eb-8d06-b79ac7e10042.png)

Shouldn't this be

```
xi = X + (WIDTH / 2)
yi = Y + (HEIGHT / 2)
```

as in, the [x,y] coordinates plus half the image?

**Comment by dbismut** [comment]
Of course, sorry, I knew I would make some typos. I fixed the Excalidraw link.

**Comment by samselikoff** [comment]
Thanks and no problem :) I'm just triple-checking my work at each step because I'm getting tripped up at some points.

Next question: `xo` needs to be calculated as of the first frame and held there. Correct? In other words, you need to introduce first/memo to get it to work because otherwise, you'll be using the updated getBoundingClientRect which will throw off the calculation. Does that sound right?

**Comment by samselikoff** [comment]
IOW, memo is not just an optimization. It is needed to arrive at the correct calculation.

**Comment by dbismut** [comment]
Exactly. You need to get the bounds and scale when the gesture started, ie when `first` is true. 

Thinking about it, it think it's a bit silly to mix memo initialization and `first`, I guess only `first` should suffice. 

I've updated one of the sandboxes above to account for that.

**Comment by samselikoff** [comment]
That's exactly what I was thinking.

I think I'm going to hand-wave just a bit in my video. Here's the picture I'm thinking of using:

![image](https://user-images.githubusercontent.com/2922250/106202292-b29c5080-6187-11eb-825d-8195d9f27783.png)

The scaled image needs to be adjusted to get the green diamonds (origin of pinch) to line up. Then something like: "It turns out, we can calculate the displacement using the original image, and multiply it by the final scale, to arrive at the final scaled displacement." I think this might be the easiest way to explain.

**Comment by samselikoff** [comment]
And yep that's basically what I ended up with wrt to the memo as well:

```js
if (first) {
  let imageBounds = imageRef.current.getBoundingClientRect();
  let xTransformOrigin = imageBounds.x + imageBounds.width / 2;
  let yTransformOrigin = imageBounds.y + imageBounds.height / 2;

  memo = {
    xDisplacement: xTransformOrigin - xPinchOrigin,
    yDisplacement: yTransformOrigin - yPinchOrigin,
  };
}
```

(This is the first pass, then I introduce compensating for initial value of x/y, then introduce compensating for initial value of scale).

**Comment by samselikoff** [comment]
I think my picture is wrong. Working on something.

**Comment by dbismut** [comment]
Maybe you don't need to go into deep explanation in the video and just link to the drawing in the description. It's not hard math but it might divert people's attention and make the impl sound more complex than it is really?

**Comment by samselikoff** [comment]
![image](https://user-images.githubusercontent.com/2922250/106207061-1ece8280-618f-11eb-945a-d1b0a33f01fb.png)

I think this is the right image, and I can hand-wave away the details and link to your Excalidraw. I think with this pic I can explain that the distance between the two green diamonds, is the original displacement distance times the scale factor. And then go from there.

Think it's all finally clicking so I should be able to record soon! Thanks again for sticking through it with me :)

**Comment by dbismut** [comment]
Sure! Good luck with the recording, let me know if you need anything.

**Comment by samselikoff** [comment]
Does `first` offer anything over doing something like

```js
memo ??= {
  imageBounds: imageRef.current.getBoundingClientRect(),
  crop
}
```

?

**Comment by dbismut** [comment]
In that case no, maybe that one is slightly better indeed, I'll steal it.
