### ISSUE TITLE
onPointerEnter/onPointerLeave handlers are not reset on change if I use domTarget instead of bind()

### ISSUE THREAD

**Issue by tokarchyn** [pmndrs/react-use-gesture#263]
**Describe the bug**
If I use useGesture callback, provide in config reference to element (domTarget), handlers for onPointerEnter/onPointerLeave, which use some variables from component's function scope for example, I want those handlers to be reset in case some of those variables change, but it does not happen. On the other hand, if I use just bind() instead of setting domTarget, everything works as expected.

**Sandbox or Video**
Here is reproduction of bug: https://codesandbox.io/s/usegesturepointerbug-8f4ir?file=/src/index.js
If you hover mouse over the red element, in console you will see counter value. After click on "Increment" button, the next hovers should print new value, but instead, they print the first one (when component was initilized).

**Information:**
 - React Use Gesture version: 9.0.0

**Comment by dbismut** [comment]
Hi @tokarchyn good catch! Just published v9.0.3 which should fix this. Thanks for reporting this.

**Comment by tokarchyn** [comment]
Yes, I've tried it and can confirm that bug is fixed. @dbismut thank you for your contribution to this awesome library 😉
