### ISSUE TITLE
cancel() causes callback to be called twice

### ISSUE THREAD

**Issue by niklaas** [pmndrs/react-use-gesture#265]
**Describe the bug**
This has already been described in #52 . Using `cancel()` all following code gets called twice.

**Sandbox or Video**
https://codesandbox.io/s/prod-dream-w99zh which is forked from the official example https://codesandbox.io/embed/n9vo1my91p. The only changes I made are:

1. increasing the version of `react-use-gesture` to `v9.0.2` from `v5.*`.
2. Using `useDrag(...` instead of `useGesture(...` (because the API seems to have changed).

Just try dragging from right to left to switch between the images. In the original versio of the codesandbox everything works as expected. In the new version, in most cases, one image is skipped (because the index is increased twice). This does not happen if `cancel()` is avoided.

**Information:**
 - React Use Gesture version: v9.0.2
 - Device: Notebook
 - OS: Mac OS 11.1
 - Browser FF 86.0

**Checklist:**
  - [X] I've rad the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
The official example sits in the lib repo (it's not the homepage of the readme). 

https://codesandbox.io/embed/v364z

**Comment by niklaas** [comment]
I see. Probably we should update the link for "View Pager" on https://www.react-spring.io/docs/hooks/examples then.
