### ISSUE TITLE
QUESTION: Mouse vs touch movement X Y calibration to viewport px is different. How do you calibrate 1:1 to px?

### ISSUE THREAD

**Issue by n8sabes** [pmndrs/react-use-gesture#266]
`useDrag` produces different x y calibration ratios with the viewport depending upon the input source.

For example, a movement `mx` result of 1 is not equal to 1px when input is from a mouse in a browser. However, it is correct 1:1 when input is from a touch device.

How do you calibrate this?

**Comment by dbismut** [comment]
What do you mean? mouse events are in pixel coordinates as far as I know. Can you show a sandbox illustrating the problem?

**Comment by n8sabes** [comment]
Thanks @dbismut.

Upon further investigation, this was an css related issue and unrelated. It was odd that touch worked perfectly while mouse input would produce different behavior.

Closing.

**Comment by dbismut** [comment]
`touch-action: none`, am I right?

**Comment by n8sabes** [comment]
Indeed, plus I had overly complex flexbox and perspective css that adjusted offsets further complicating the situation. It's working perfectly now, but made me scratch my head for a bit.
