### ISSUE TITLE
transform to a perspective results in unexpected values

### ISSUE THREAD

**Issue by micha149** [pmndrs/react-use-gesture#271]
**Describe the bug**
I'm using the `transform` option with a raycaster to transform the position on screen to a position on a plane in a 3d scene. racasting works fine but the drag handler is not called as expected. First it did not respond immediately, but I have no threshold configured. The larger the screen the stronger the effect (open the sandbox output in a new tab). Secondly the `y` coordinate is always `0`.

**Sandbox**
I created a sandbox with a minimal example. Please don't comment the inefficient instancing in the transform function. It's just for simplicity. 😄 

https://codesandbox.io/s/use-gesture-transform-behavior-6fk7u?file=/src/Box.js

**Information:**
 - React Use Gesture version: 9.1.1
 - Device: Mac
 - OS: 10.15.7
 - Browser Chrome 88.0.4324.192

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Got it. I can see the issue, I'll drop a fix in the next hours.

**Comment by micha149** [comment]
Cool. I also had a quick look on the sources but can't follow where the problem might be.

Thanks!

**Comment by dbismut** [comment]
Should be fixed in 9.1.2 see https://codesandbox.io/s/use-gesture-transform-behavior-forked-hi8hg

The problem was that I assumed that all transform functions would keep the `[0,0]` origin the same, which is obviously a lame assumption.

Here's the issue in details.

- the `threshold` option is supposed to be given in viewport coordinates (you usually want to trigger a gesture based on an absolute displacement from the pointer).
- therefore, I had to compare the *transformed* `threshold` to the *transformed* `movement`. But with a `[0,0]` threshold (ie the movement should happen immediately) being possibly converted to, let's say `[1,1]`, then in three js space this would artificially create a pretty big threshold!
- therefore the fix is to compare the movement to `subV(transform(config.threshold), transform([0,0]))` (`subV` is a utility that subtract two vectors).

Hope this fixes it!

**Comment by micha149** [comment]
👍 Works now es expect. Thanks a lot for this quick fix!

**Comment by micha149** [comment]
OK, there is still some strange behavior I didn't noticed before.

I switched to a perspective camera just for playin' around and the box moves not as fast as my mouse. So I added some `console.log` statements and noticed, that the transform params `aren't` my mouse position. In a ortographic projection this makes no difference because the angle is always the same but in a perspective projection the angle increases from the center to the edges of my screen.

Also  `state.xy` isn't the expected value so I think there is still something broken.

**Comment by dbismut** [comment]
This is related to what I'm explaining above. `transform` isn't just used for mouse coordinates but also to evaluate other parameters such as `threshold` that is expressed in screen coordinates. 

If the logic you need should only run for the pointer, then you need to set it into the gesture handler.

**Comment by micha149** [comment]
Ah, ok. Now I understand your fix. But…

I agree that a threshold makes sense in screen space because when you click something you wan't to call the drag handler for example. But why calling the transform for so much values when they could be compared as raw values?

On the other hand it could make sense to express the threshold in world space too. For example you create a grid and want an element to only start dragging when you pass a half of a grid cell. In that case you need to express it in world space.

And by the way: I personally expected to express the threshold in my transformed values. I think the documentation does not mention it.

Yes, I could do everything in the drag handler by myself. But I thought the key feature of this library is that it does all the repetitive tedious work like storing the start of a drag, calculating movement etc. But the most of this I have to implement on my own now. The 3D example in the documentation also raises unfulfilled expectations, as a transform only works in orthogonal spaces. And usually one works with perspective cameras. 😞

**Comment by dbismut** [comment]
I'll try to be as constructive as I can.

> And by the way: I personally expected to express the threshold in my transformed values. I think the documentation does not mention it.

Here is what the docs say in the `transform` paragraph:

_Note that bounds or initial values are expected to be expressed in the new space coordinates. Only threshold always refers to screen pixel values._

Maybe that's not visible or clear enough, but it's in there!

> On the other hand it could make sense to express the threshold in world space too. For example you create a grid and want an element to only start dragging when you pass a half of a grid cell. In that case you need to express it in world space.

I agree that in some cases it would make sense. But `threshold` is originally designed to detect unintentional gestures, which only make sense when expressed in screen space. Note that the `filterTaps` option resolves to a `[3,3]` threshold.

> But why calling the transform for so much values when they could be compared as raw values?

I'm not sure what you're referring to by _"so much values"_? I don't understand this part.

> Yes, I could do everything in the drag handler by myself. But I thought the key feature of this library is that it does all the repetitive tedious work like storing the start of a drag, calculating movement etc. But the most of this I have to implement on my own now. The 3D example in the documentation also raises unfulfilled expectations, as a transform only works in orthogonal spaces. And usually one works with perspective cameras. 😞

The goal of this library is to make things easier for most of use cases. It doesn't guarantee that there won't be complicated logic in some situations. use gesture is being used a lot AFAIK in the r3f space, and you're welcomed to join the Discord channel to discuss this with the community.

I think the assumption that the `transform` function would only be called for pointer coordinates is wrong. I agree that there might be other ways to deal with threshold, but `transform` is not the place where to perform UI logic, and shouldn't be. It's just a function that maps your space to the screen.

I'm planning to work on v10 at some point, and one of my objectives is to streamline the way it works with r3f (as r3f passes augmented events which the lib is not considering atm). You're welcome to contribute or open the way.

**Comment by micha149** [comment]
Don't get me wrong I want to be constructive too.

> in the `transform` paragraph

OK I just looked in the `threshold` for this particular information. Sorry for that.

> I'm not sure what you're referring to by "so much values"? I don't understand this part.

I want to ask if there is a technical reason for transforming _start_  and _current position_  for checking the threshold. I would expect that the screen x and y ist stored on start. Then on every move its compared to the new x and y to check the threshold. Then when the threshold is reached, a state will be constructed by piping all the screen positions though `transform` and calculating `movement`, `offset` etc. in transformed space.

For me the current behavior works fine, because I'm working on an orthographic projection. I just thought that someone else may run into unexpected results when using transform for a perspective projection. I am wondering how all the other r3f projects implement dragging in a perspective…

Nevertheless thank you for your support.

**Comment by dbismut** [comment]
The way it works is that the pointer coordinates are transformed when fetched, so that the handler don't even bother storing the screen coordinates. The logic is what you described though, only that there's some hidden attributes that are stored (like `_movement` which is the actual `movement` ignoring `threshold`. I'll have a deeper look at how to address your issue though.

Again, I know that r3f does intersection computation and adds that info to the event, so maybe there's a way to make your use case even simpler. Did you ever look at these values btw?
