### ISSUE TITLE
useScroll doesn't return direction, distance etc.

### ISSUE THREAD

**Issue by mattmuirhead** [pmndrs/react-use-gesture#272]
**Describe the bug**
When using useScroll, direction and distance aren't returned. However when using useWheel they are.

**Sandbox or Video**
Issue can be seen in the dev console
https://codesandbox.io/s/cranky-tu-pl0lq?file=/src/App.js

**Comment by dbismut** [comment]
Hi @mattmuirhead thanks for the sandbox. Note that it's not using the last version of the lib. Is there any reason why you're using `document` instead of `window`?

**Comment by mattmuirhead** [comment]
Hi @dbismut, sorry have updated the sandbox now. Also updated the sandbox to be more reflective of what we're trying to achieve. We're not scrolling the main document, we're scrolling a div inside the document. However, we don't have access to bind the useScroll to the div. https://codesandbox.io/s/cranky-tu-pl0lq?file=/src/App.js

**Comment by dbismut** [comment]
You mean you can't do this?
https://codesandbox.io/s/recursing-star-6ivzm?file=/src/App.js

**Comment by mattmuirhead** [comment]
Unfortunately not. The component we're using passes the ref to the inner div rather than the div that scrolls

**Comment by dbismut** [comment]
Would this be an acceptable solution: https://codesandbox.io/s/recursing-star-6ivzm?
Unfortunately, the only fix that I could make is to change the target for scroll events from `currentTaget` to `target`. But that would probably lead to unwanted behavior in some circumstances.

Note that we've diverted from the original issue, which is now that you'd want `useScroll` to intercept scroll events attached to any children of the `domTarget` (which doesn't feel right imo).

**Comment by mattmuirhead** [comment]
Thanks for the reply. I'll look into your solution.
Is there a reason though why useWheel returns the correct data but useScroll doesn't when targeting the document?

**Comment by dbismut** [comment]
Yes. Elements intercept wheel events more or less the same way they do for pointer events. scroll events only happen when an element actually scroll. In your case window will intercept all wheel events that propagates down to it. But if the window doesn’t scroll it won’t fire any scroll events.
