### ISSUE TITLE
Pinch and zoom on video wall is too sensitive

### ISSUE THREAD

**Issue by SevenSinS02** [pmndrs/react-use-gesture#281]
**Describe the bug**
The pinch and zoom seems to be very sensitive when using with the video wall. I've done the same on a laptop, phone, desktop and works perfectly fine. However, it all goes weird when using on the video wall. I'm really confused as to why the sudden change in behaviour.
I would be really grateful if you could help out.

**Sandbox or Video**
I've used your code for the pan and zoom.
https://codesandbox.io/s/elated-lichterman-oj203

Below is a video to better explain what I'm facing.
https://drive.google.com/file/d/1j-zJjAMNuCAy-rgzakcBItUS9_c-C7mG/view?usp=sharing

**Information:**
 - React Use Gesture version: 9.1.3
 - Device: 2X2 video wall
 - OS: mac os mojave
 - Browser : Chrome

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/).
  - [X] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hi, please provide a sandbox, I'm not sure what a video wall is.

**Comment by SevenSinS02** [comment]
Hi @dbismut. It's updated. Didn't realise I had already created an issue without the sandbox and the video. Apologies.

**Comment by dbismut** [comment]
Hey, no problem. The video requires access you should let anyone view the link ;)

**Comment by SevenSinS02** [comment]
Apologies. Should be possible now.

**Comment by dbismut** [comment]
I'll get back to you later today. I think this is due to the stupid pinch approximation I've implemented and that I should fix in v10.

**Comment by dbismut** [comment]
Hey @SevenSinS02 have a look at this comment https://github.com/pmndrs/react-use-gesture/issues/260#issuecomment-781272882. 

Try installing 9.1.0-alpha.1 and see if this works out as described in there. 

Let me know if you need further guidance.

**Comment by SevenSinS02** [comment]
@dbismut i will give that a try! Thanks a lot :)

**Comment by SevenSinS02** [comment]
Hi @dbismut . The sensitivity is still high. Any idea how I can adjust the pinch speed/ sensitivity.

**Comment by dbismut** [comment]
Did you try multiplying the scale multiplier by a factor lower than 1?

**Comment by dbismut** [comment]
This sort of issue generally happens when touch-action is not set to none. But I can see that it is indeed set in your sandbox. What is the browser used by the wall?

**Comment by SevenSinS02** [comment]
it's chrome itself. Ah! I didn't set it when using it with electron js. Thanks!!!
