### ISSUE TITLE
Not working anymore with @react-three/fiber Canvas

### ISSUE THREAD

**Issue by CptCompiler** [pmndrs/react-use-gesture#283]
**Describe the bug**
Doesn't seem to work anymore with @react-three/fiber on the Canvas element

**Sandbox or Video**
https://codesandbox.io/s/r3f-basic-demo-forked-3p93w?file=/src/App.js

**Comment by dbismut** [comment]
Hi @CptCompiler this is not related to react-use-gesture. As you can see from your upgraded sandbox, Canvas doesn't seem to accept pointer handlers. I'm investigating with the team, but as a workaround you can most definitely spread the handlers inside a wrapping div, resulting in the same output.

https://codesandbox.io/s/r3f-basic-demo-forked-vgygr?file=/src/App.js

**Comment by CptCompiler** [comment]
Ok, thank you very much. I will try that.

Very nice work by the way.
