### ISSUE TITLE
Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by nakamuraos** [pmndrs/react-use-gesture#296]
**Describe the bug**
> Drag will raise an error `Cannot read property 'current' of undefined`

**Sandbox or Video**
> https://codesandbox.io/s/multi-gesture-card-forked-9jrn1

**Information:**
 - React Use Gesture version: 9.1.3
 - Device: All
 - OS: All
 - Browser: All

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
This is a misuse of react-spring v9 api.
Here's a correct version: https://codesandbox.io/s/multi-gesture-card-forked-flnqp

**Comment by nakamuraos** [comment]
Thank you very much @dbismut. Can you update examples on codesandbox?

**Comment by dbismut** [comment]
I'm going to release V10 shortly.
